version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
  app:
    container_name: app
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/app
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/dump/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data/:/var/lib/postgresql/data:rw
    env_file:
      - docker.env
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
      - 15672:15672
