version: '3.8'

services:
  nginx:
    image: nginx:1.20-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
  app:
    container_name: app
    build:
      context: docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/app
    restart: always
    tty: true
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/dump/:/docker-entrypoint-initdb.d
      - ./docker/postgres/data/:/var/lib/postgresql/data:rw
    env_file:
      - docker.env
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
  maildev:
    image: maildev/maildev
    container_name: mailer
    ports:
      - "8081:80"
    restart: always
