#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#basketAddItem:
 # path:      /basket/{id}
# requirements:
 #       number: \d+
authentication_token:
  path: /authentication_token
  methods: ['POST']